# Generated by Django 4.0.2 on 2022-02-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
    ]
