# Generated by Django 4.0.1 on 2022-03-16 05:46

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(error_messages={'unique': '이미 있는 제목입니다'}, max_length=50, unique=True, validators=[posts.validators.validate_symbols]),
        ),
    ]
