# Generated by Django 4.0.1 on 2022-03-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
